"""Export a checkpoint as int6 weights and measure the actual exported model."""

from __future__ import annotations

import argparse
import gzip
import hashlib
import json
import subprocess
from pathlib import Path

import numpy as np
import torch

from model import TimeTagger
from train import Dataset, evaluate
from calibrate import calibrate

ROOT = Path(__file__).resolve().parent.parent
ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"


def lineage(checkpoint: Path) -> list[dict]:
    result = []
    seen = set()
    while checkpoint:
        key = checkpoint.resolve()
        if key in seen:
            raise ValueError("Checkpoint ancestry contains a cycle")
        seen.add(key)
        saved = torch.load(checkpoint, map_location="cpu", weights_only=True)
        result.append(
            {
                "checkpoint": str(checkpoint),
                "sha256": hashlib.sha256(checkpoint.read_bytes()).hexdigest(),
                "epoch": saved["epoch"],
                "trainingTokens": saved["tokensSeen"],
            }
        )
        parent = saved["config"].get("init")
        if not parent:
            break
        checkpoint = ROOT / parent
    return result


def export(
    checkpoint: Path, destination: Path, report_path: Path, parity_prefix: Path | None
):
    torch.set_num_threads(4)
    saved = torch.load(checkpoint, map_location="cpu", weights_only=True)
    reference = TimeTagger(saved["model"]["embedding"].shape[0]).eval()
    reference.load_state_dict(saved["model"])
    encoded = []
    segments = []
    decoded = {}
    offset = 0
    for name, parameter in reference.named_parameters():
        values = parameter.detach().numpy().astype(np.float32)
        scale = np.float32(max(float(np.abs(values).max()) / 31, 1e-8))
        integers = np.clip(np.rint(values / scale), -31, 31).astype(np.int8)
        flat = integers.reshape(-1)
        encoded.extend(
            ALPHABET[int(value) * 2 if value >= 0 else -int(value) * 2 - 1]
            for value in flat
        )
        segments.append(
            {
                "name": name,
                "offset": offset,
                "length": int(flat.size),
                "shape": list(values.shape),
                "scale": float(scale),
            }
        )
        decoded[name] = torch.from_numpy(integers.astype(np.float32) * scale)
        offset += flat.size
    reference.load_state_dict(decoded)
    reference.qat = (
        False  # These parameters already contain the exact decoded wire values.
    )
    reference.storage_f16 = saved["config"].get("storage", "f16") == "f16"
    reference.reference_scan = True

    config = saved["config"]
    data = ROOT / "data/synth" / config["run"]
    validation = Dataset(data / "validation")
    heldout = Dataset(data / "heldout")
    labels = saved.get("labelNames", list(validation.manifest["labelCounts"]))
    calibration = calibrate(
        reference, {"validation": validation, "heldoutDevelopment": heldout}
    )
    threshold = calibration["threshold"]
    artifact = {
        "version": 1,
        "hidden": 32,
        "featureRows": reference.feature_rows,
        "storage": saved["config"].get("storage", "f16"),
        "roleClasses": 40,
        "boundaryThreshold": threshold,
        "labels": labels,
        "q": "".join(encoded),
        "segments": segments,
    }
    source = (
        "// Generated by training/export.py. The encoded string is model data, not source logic.\nexport const weights = "
        + json.dumps(artifact, separators=(",", ":"))
        + " as const;\n"
    )
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(source)
    brotli_script = "import {readFileSync} from 'node:fs';import {brotliCompressSync} from 'node:zlib';process.stdout.write(String(brotliCompressSync(readFileSync(process.argv[1])).length));"
    brotli = int(
        subprocess.check_output(
            ["node", "--input-type=module", "-e", brotli_script, str(destination)],
            cwd=ROOT,
            text=True,
        )
    )
    metrics = {
        "validation": evaluate(reference, validation, 256, "cpu", threshold),
        "heldout": evaluate(reference, heldout, 256, "cpu", threshold),
    }
    ancestry = lineage(checkpoint)
    report = {
        "checkpoint": str(checkpoint),
        "checkpointSha256": hashlib.sha256(checkpoint.read_bytes()).hexdigest(),
        "artifactSha256": hashlib.sha256(source.encode()).hexdigest(),
        "boundaryThreshold": threshold,
        "calibration": calibration,
        "epoch": saved["epoch"],
        "tokensSeenAtCheckpoint": sum(item["trainingTokens"] for item in ancestry),
        "lineage": ancestry,
        "parameters": int(offset),
        "quantizationBits": 6,
        "logicalPackedBytes": int(np.ceil(offset * 6 / 8)),
        "encodedCharacters": len(encoded),
        "moduleBytes": len(source.encode()),
        "moduleGzipBytes": len(gzip.compress(source.encode(), mtime=0)),
        "moduleBrotliBytes": brotli,
        "labels": labels,
        "metrics": metrics,
        "scope": "Exact decoded int6 weights, sequential CPU PyTorch inference reference with the recorded intermediate precision. Training uses the mathematically equivalent parallel affine scan. Browser parity and end-to-end schedule accuracy are separate gates.",
    }
    if parity_prefix:
        indices = np.arange(min(512, len(heldout)))
        rows, targets, boundaries, valid, neighbors = heldout.batch(indices, "cpu")
        with torch.no_grad():
            logits, clause_logits = reference(rows, valid, neighbors)
        parity_prefix.parent.mkdir(parents=True, exist_ok=True)
        np.savez_compressed(
            f"{parity_prefix}.npz",
            rows=rows.numpy(),
            targets=targets.numpy(),
            boundaries=boundaries.numpy(),
            valid=valid.numpy(),
            neighbors=neighbors.numpy(),
            logits=logits.numpy(),
            clause_logits=clause_logits.numpy(),
        )
        lengths = valid.sum(1).numpy().astype(np.uint32)
        offsets = np.concatenate(
            (np.array([0], dtype=np.uint32), np.cumsum(lengths, dtype=np.uint32))
        )
        wire_rows = rows.numpy()[valid.numpy()].astype(np.uint16)
        wire_logits = logits.numpy()[valid.numpy()].astype(np.float32)
        wire_boundaries = clause_logits.numpy()[valid.numpy()].astype(np.float32)
        for suffix, values in [
            ("rows", wire_rows),
            ("logits", wire_logits),
            ("boundaries", wire_boundaries),
            ("offsets", offsets),
        ]:
            values.tofile(f"{parity_prefix}.{suffix}.bin")
        report["parity"] = {
            "prefix": str(parity_prefix),
            "sequences": len(indices),
            "tokens": int(lengths.sum()),
            "rowsPerToken": 17,
            "rolesPerToken": 40,
            "boundaryThreshold": threshold,
        }
        Path(f"{parity_prefix}.json").write_text(
            json.dumps(report["parity"], indent=2) + "\n"
        )
    report_path.parent.mkdir(parents=True, exist_ok=True)
    source_directory = ROOT / "training/exports" / report["artifactSha256"] / "source"
    report["exportSourceDirectory"] = str(source_directory.relative_to(ROOT))
    report["exportSourceHashes"] = {}
    for name in [
        "training/export.py",
        "training/calibrate.py",
        "training/model.py",
        "training/train.py",
        "training/uv.lock",
    ]:
        content = (ROOT / name).read_bytes()
        target = source_directory / name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(content)
        report["exportSourceHashes"][name] = hashlib.sha256(content).hexdigest()
    report_path.write_text(json.dumps(report, indent=2) + "\n")
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--checkpoint", type=Path, required=True)
    parser.add_argument("--out", type=Path, default=Path("src/model/weights.gen.ts"))
    parser.add_argument(
        "--report", type=Path, default=Path("training/export-report.json")
    )
    parser.add_argument("--parity", type=Path, default=Path("training/parity"))
    args = parser.parse_args()
    export(args.checkpoint, args.out, args.report, args.parity)
