directories:
  output: video/output
  cache: video/output/cache
camera:
  background_color: "#050607"
  resolution: (1920, 1080)
  fps: 60
text:
  font: "Geist Mono"
file_writer:
  video_codec: libx264
  pixel_format: yuv420p
